# Generated by Django 4.2.4 on 2023-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='courses',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python3'), ('Django', 'Django Framework'), ('C++', 'C++')], default='Python', max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Email'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(help_text='Name should be within 30 letters', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.BigIntegerField(help_text='Phone number should be 10 digits'),
        ),
    ]
