# Generated by Django 4.2.4 on 2023-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_enquiry_courses_alter_enquiry_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Joined', 'Joined'), ('Not Responding', 'Not Respondinig')], default='Interested', max_length=50),
        ),
    ]
