# Generated by Django 4.2.4 on 2023-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_enquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('course_name', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Django', 'Django')], default='C', max_length=30)),
                ('course_fee', models.DecimalField(decimal_places=5, max_digits=7)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('On Going', 'On Going'), ('Hold', 'Hold'), ('Discountinued', 'Discontinued'), ('Completed', 'Completed')], default='Yet to Start', max_length=30)),
            ],
        ),
    ]
