# Generated by Django 4.2.4 on 2023-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_students_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_fee',
            field=models.IntegerField(),
        ),
    ]
